name: Build and Test.

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_MODE: Release
  SOLUTION_NAME : Serilog.FluentDestructuring.sln

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout.
        uses: actions/checkout@v3

      - name: Install .NET.
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies.
        run: dotnet restore

      - name: Build.
        run: dotnet build ${{ env.SOLUTION_NAME }} --configuration ${{ env.BUILD_MODE }} --no-restore

      - name: Test.
        run: dotnet test ${{ env.SOLUTION_NAME }} --no-build --verbosity normal --configuration ${{ env.BUILD_MODE }}